volumes:
  rabbitmq:
    driver: local
  redis:
    driver: local
  postgres:
    driver: local
  # pgadmin:
  #   driver: local
  # redisinsight:
  #   driver: local
  # oracle_db:
  #   driver: local

services:
  # ---------------------------------------------------------------------------------
  # RabbitMQ
  # ---------------------------------------------------------------------------------

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4-management-alpine
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: test
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  # ---------------------------------------------------------------------------------
  # Redis
  # ---------------------------------------------------------------------------------

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  # ---------------------------------------------------------------------------------
  # Postgres
  # ---------------------------------------------------------------------------------

  postgres_db:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

# ---------------------------------------------------------------------------------
# Oracle
# ---------------------------------------------------------------------------------

# oracle_db:
#   container_name: oracle-free
#   image: container-registry.oracle.com/database/free:latest
#   restart: always
#   ports:
#     - "1521:1521"
#     - "5500:5500"
#   environment:
#     - ORACLE_PWD=test
#   volumes:
#     - oracle_db:/opt/oracle/oradata

# ---------------------------------------------------------------------------------
# PgAdmin
# ---------------------------------------------------------------------------------

  # pg-admin:
  #   container_name: pg_admin
  #   image: dpage/pgadmin4:latest
  #   restart: always
  #   ports:
  #     - "5050:80"
  #   #in pgAdmin set Host name/address to host.docker.internal or postgres_db in linux
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=test@pandatech.it
  #     - PGADMIN_DEFAULT_PASSWORD=test
  #   volumes:
  #     - pgadmin:/var/lib/pgadmin

# ---------------------------------------------------------------------------------
# Redis Insight
# ---------------------------------------------------------------------------------

# redisinsight:
#   container_name: redisinsight
#   image: redis/redisinsight:latest
#   restart: always
#   ports:
#     - "5540:5540"
#   volumes:
#    - redisinsight:/db
