services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config/config.yaml
    volumes:
      - ./config/loki-config.yaml:/etc/loki/config/config.yaml:ro

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    ports:
      - "14250:14250"  # gRPC
      - "4317:4317"    # OTEL gRPC
      - "4318:4318"    # OTEL HTTP
    command: -config.file=/etc/tempo/config/config.yaml
    volumes:
      - ./config/tempo-config.yaml:/etc/tempo/config/config.yaml:ro

  mimir:
    image: grafana/mimir:latest
    container_name: mimir
    ports:
      - "9009:9009"
    command: -config.file=/etc/mimir/config/config.yaml
    volumes:
      - ./config/mimir-config.yaml:/etc/mimir/config/config.yaml:ro

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - loki
      - tempo
      - mimir
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin