server:
  http_listen_port: 9009

multitenancy_enabled: true

ingester:
  lifecycler:
    join_after: 0s
    ring:
      kvstore:
        store: inmemory

distributor:
  ring:
    kvstore:
      store: inmemory

store:
  backend: filesystem
  filesystem:
    dir: /tmp/mimir/data

query_range:
  cache_results: false