server:
  http_listen_port: 3200

distributor:
  receivers:
    jaeger:
      protocols:
        thrift_compact:
        thrift_binary:
        thrift_http:
        grpc:
    otlp:
      protocols:
        grpc:
        http:
    zipkin:
      port: 9411

ingester:
  trace_idle_period: 10s
  max_block_duration: 5m

compactor:
  compaction_window: 5m

querier:
  frontend_worker:
    frontend_address: frontend:9095

query_frontend:
  downstream_url: http://querier:16686

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/traces