ALTER SESSION SET "_oracle_script"=true;
CREATE USER test IDENTIFIED BY test;
ALTER USER test IDENTIFIED BY test;
GRANT CREATE SESSION TO test;
GRANT RESOURCE TO test;
GRANT CREATE TABLE TO test;
GRANT CREATE VIEW TO test;
GRANT CREATE PROCEDURE TO test;
GRANT CREATE SEQUENCE TO test;